### ISSUE TITLE
panic when stress testing if we got the "error writing to buffer io.Writer" error

### ISSUE THREAD

**Issue by zhironghsu** [mochi-co/mqtt#107]
`mqtt-stresser.exe -broker tcps://localhost:18883 -skip-tls-verification -num-clients 10 -num-messages 80000 -rampup-delay 1s -rampup-size 10 -global-timeout 180s -timeout 20s`

2022/11/07 19:12:35 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61022: wsasend: An existing connection was forcibly closed by the remote host.
2022/11/07 19:20:38 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61125: wsasend: An existing connection was forcibly closed by the remote host.
2022/11/07 19:20:38 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61126: wsasend: An existing connection was forcibly closed by the remote host.
2022/11/07 19:20:38 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61128: wsasend: An existing connection was forcibly closed by the remote host.
2022/11/07 19:20:38 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61127: wsasend: An existing connection was forcibly closed by the remote host.
2022/11/07 19:20:38 error writing to buffer io.Writer; write tcp 127.0.0.1:18883->127.0.0.1:61130: wsasend: An existing connection was forcibly closed by the remote host.
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x10ff227]

goroutine 150 [running]:
github.com/mochi-co/mqtt/server/internal/circ.(*Writer).Write(0x0, {0xc0048eaa00, 0x4e, 0xf?})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/internal/circ/writer.go:80 +0x27
github.com/mochi-co/mqtt/server/internal/clients.(*Client).WritePacket(_, {{0x4c, 0x3, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/internal/clients/clients.go:500 +0x3fd
github.com/mochi-co/mqtt/server.(*Server).writeClient(_, _, {{0x0, 0x3, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/server.go:440 +0x5d
github.com/mochi-co/mqtt/server.(*Server).publishToSubscribers(_, {{0x4c, 0x3, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, ...}, ...})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/server.go:690 +0x634
github.com/mochi-co/mqtt/server.(*Server).processPublish(_, _, {{0x4c, 0x3, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/server.go:613 +0x698
github.com/mochi-co/mqtt/server.(*Server).processPacket(_, _, {{0x4c, 0x3, 0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/server.go:463 +0x13b
github.com/mochi-co/mqtt/server/internal/clients.(*Client).Read(0xc0009087e0, 0xc0001d1a58)
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/internal/clients/clients.go:386 +0x19d
github.com/mochi-co/mqtt/server.(*Server).EstablishConnection(0xc0001162c0, {0x11fd4b8, 0x2}, {0x1285e78, 0xc0004c0380}, {0x1283ca8?, 0x147d0d8?})
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/server.go:364 +0x1152
github.com/mochi-co/mqtt/server/listeners.(*TCP).Serve.func1()
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/listeners/tcp.go:106 +0x3d
created by github.com/mochi-co/mqtt/server/listeners.(*TCP).Serve
        C:/Users/test/go/pkg/mod/github.com/mochi-co/mqtt@v1.3.2/server/listeners/tcp.go:105 +0xea

**Comment by mochi-co** [comment]
Happy to say this issue is fixed in v2.0.0, which is a complete rebuild of the broker. It will be ready for release soon (next 2 weeks?), but it was a much bigger task than initially anticipated.

**Comment by mochi-co** [comment]
This issue has been resolved in v2.0.0
