### ISSUE TITLE
When will the second version be released

### ISSUE THREAD

**Issue by tmq-rs** [mochi-co/mqtt#108]

**Comment by mochi-co** [comment]
Hi @toable, thanks for your question! Version 2.0.0 is roughly 98% complete, however the last 2% is a bit challenging as I have discovered an inconsistency between the mqtt v5 flow control I've implemented and the flow control tests in the Paho Interoperability tests for v5. Once this is resolved, I will refactor and cleanup the codebase, and then it should be ready for pre-release. I will update the README when I feel confident to give an accurate timeline.

**Comment by mochi-co** [comment]
v2.0.0 has been released :) Thank you for your patience.
