### ISSUE TITLE
Messages silently dropped

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#109]
Hi,

First of all, I want to thank you for this great module!

We have embedded this module into our application, we noticed messages received were lower than expected. After eliminating all possibilities, we started investigate deeper into the library, we noticed the BufferSize setting is not only the default size, it's also the absolute limit (wasn't clear from the documentation) for the connection (one for read and one for write). When a single MQTT message is greater than the BufferSize, it will be blocked until the connection timeout, this also does not trigger the on(OnProcess)Message events.

We expect to handle very large number of connections, the vast majority of the message is only couple KB (but very small fraction can be many hundred KB or larger), the message frequency is once a minute. Given module will allocate 2x of the BufferSize (read and write) for each connection, we set a relatively small BufferSize. However, to handle few corner case messages, we would need to dramatically increase the BufferSize, which will substantially increase the total memory requirement.

There are few possible improvements:
1. Reject message (immediately disconnect client) if size is >BufferSize (maybe rename?) after cl.ReadFixedHeader, trigger an event. Given the current behavior is silently deadlocked in reading and result in connection disconnect due to timeout, this has the same result but fail faster and event callback to upper layer for visibility.
2. For long lived connections where message frequency is even once a minute, allocate/gc buffer as needed can be amortized, the benefit of using sync.Pool is diminished. The much smaller memory footprint for large concurrent connections can outweight the reduction in memory allocation/gc.
3. Pre-allocates BufferSize, but dynamically allocates (or expand) buffer as needed.

**Comment by mochi-co** [comment]
Thanks @thedevop - You should find this resolved in v2.0.0 :)
