### ISSUE TITLE
Wrong go versioning in v2.0.0

### ISSUE THREAD

**Issue by bkupidura** [mochi-co/mqtt#111]
Looks like versioning in v2.0.0 is broken.

```
% go get -v github.com/mochi-co/mqtt@latest
go: added github.com/mochi-co/mqtt v1.3.2
```

```
% go get -v github.com/mochi-co/mqtt@v2.0.0
go: github.com/mochi-co/mqtt@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/mochi-co/mqtt/v2")
```

**Comment by mochi-co** [comment]
Looks like it's related to https://github.com/golang/go/issues/35732 (eg.  https://github.com/prometheus/prometheus/issues/8852). This is unexpected - researching solution now. Let me know if you have any ideas 👍🏻

**Comment by mochi-co** [comment]
https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by mochi-co** [comment]
v2.0.1 should now be pointing to github.com/mochi-co/mqtt/v2 - it doesn't seem to import on my machine, I still get the following error:
```
% go mod tidy
go: finding module for package github.com/mochi-co/mqtt/v2
go: finding module for package github.com/mochi-co/mqtt/v2/listeners
go: finding module for package github.com/mochi-co/mqtt/v2/hooks/auth
github.com/mochi-co/tmp imports
        github.com/mochi-co/mqtt/v2: module github.com/mochi-co/mqtt@latest found (v1.3.2), but does not contain package github.com/mochi-co/mqtt/v2
github.com/mochi-co/tmp imports
        github.com/mochi-co/mqtt/v2/hooks/auth: module github.com/mochi-co/mqtt@latest found (v1.3.2), but does not contain package github.com/mochi-co/mqtt/v2/hooks/auth
github.com/mochi-co/tmp imports
        github.com/mochi-co/mqtt/v2/listeners: module github.com/mochi-co/mqtt@latest found (v1.3.2), but does not contain package github.com/mochi-co/mqtt/v2/listeners
```

**Comment by mochi-co** [comment]
Using go mod tidy with github.com/mochi-co/mqtt/v2 imports now appears to pull the correct release, but @latest still seems to be pointing to v1.3.2 for some reason.
```
% go get -v github.com/mochi-co/mqtt@latest
go: added github.com/mochi-co/mqtt v1.3.2
```

**Comment by mochi-co** [comment]
It appears this is the correct way things work now once you move to go versioning for v2 or above: you have to import `"github.com/mochi-co/mqtt/v2"` and then `go mod tidy` to get the latest v2 version.

I have tested this against https://github.com/hajimehoshi/ebiten and https://github.com/go-redis/redis both have the same issue when trying to `go get` with `@latest`, so I will close this for now. I have reached out for advice and will try to fix the @latest issue if there is a solution.
