### ISSUE TITLE
Func (s * Server) Publish (topic string, payload [] byte, retain bool) error method Is the v2 version not available?

### ISSUE THREAD

**Issue by morebuff** [mochi-co/mqtt#113]
Func (s * Server) Publish (topic string, payload [] byte, retain bool) error method Is the v2 version not available?

**Comment by mochi-co** [comment]
Hi @morebuff! I can see how this would be useful. Restored as a convenience function with new signature `Publish(topic string, payload []byte, retain bool, qos byte) error` in v2.0.4 :)
