### ISSUE TITLE
Double OnPublish hook call for QoS messages

### ISSUE THREAD

**Issue by tommyminds** [mochi-co/mqtt#118]
Hi Mochi,

In the server's processPublish call, I noticed that the `OnPublish` hook is called twice for QoS messages. Both on [line 685](https://github.com/mochi-co/mqtt/blob/master/server.go#L685) and [line 730](https://github.com/mochi-co/mqtt/blob/master/server.go#L730).

Is this is a bug, or the intended behavior?

I see in the docs for the `OnPublish` hook that it allows you to modify the incoming package before it is processed. And that it differs from `OnMessage` in that regard. However, the `OnMessage` hook seems to not exist. Is the second `OnPublish` hook by any chance meant to be an `OnMessage`?

**Comment by mochi-co** [comment]
This is a bug - the second call should be
`OnPublished(cl *Client, pk packets.Packet) `. I’ll fix this this evening and also correct the related comments. Great find! Thank you, and sorry for the bug! 🙏🏻

**Comment by tommyminds** [comment]
Great! In that case I assume `OnPublished` should also be called when the function returns early on QoS 0 messages. 

Thanks for the fast responses, and no need to apologise for bugs! The library is great!

**Comment by mochi-co** [comment]
Resolved in v2.0.5 - thanks again for your help! :)
