### ISSUE TITLE
ResponseTopic and CorrelationData don't seem to work

### ISSUE THREAD

**Issue by UrsBisang** [mochi-co/mqtt#126]
Hi, I was playing a little bit with mochi and it looks interesting. I did a test setting/sending ResponseTopic and CorrelationData when publishing a message using python paho mqtt client, but it doesn't look like it is working, i.e. subscriber didn't get ResponseTopic nor CorrelationData in received message. Same test with mosquitto broker worked, so the test should be ok.

**Comment by mochi-co** [comment]
Hi @UrsBisang! 

The MQTTv5 spec: [https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901052](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901052) talks about response information here. Now that I am reading it again, it seems like it refers to response information in the Connack packet _only_, rather than all response packets. 

I will try to correct this later this evening - sorry for the oversight.

**Comment by UrsBisang** [comment]
Hi, thanks! Here some more information that might be helpful: I tried to use ResponseTopic and CorrelationData to implement a request-response style messaging pattern.

Here the test code I used (Sorry, it's in Python):

# pip install paho-mqtt
import paho.mqtt.client as mqtt
import paho.mqtt.packettypes as packettypes


def on_connect(client, userdata, message, tmp=None, properties=None):
    client.subscribe("test/request")
    properties = mqtt.Properties(packettypes.PacketTypes.PUBLISH)
    properties.CorrelationData = "<request-id>".encode('utf-8')
    properties.ResponseTopic = "test/response"
    client.publish("test/request", "test message", properties=properties)


def on_message( client, userdata, message, tmp=None):
    print(f"message properties: {message.properties}, payload={message.payload}")


client = mqtt.Client("test_client", protocol=mqtt.MQTTv5)
client.on_message = on_message
client.on_connect = on_connect

client.connect("localhost")
client.loop_forever()

---------------------------------------------

Running it against mochi broker gives the following output:

message properties: [MessageExpiryInterval : 86400], payload=b'test message'

Running it against mosquitto broker gives the following output which is what I would expect to get:

message properties: [ResponseTopic : test/response, CorrelationData : b'<request-id>'], payload=b'test message'

**Comment by mochi-co** [comment]
Fixed in v2.1.0 - Thank you @UrsBisang - your python example was very helpful in testing the solution!

**Comment by UrsBisang** [comment]
Thanks a lot for fixing it!
