### ISSUE TITLE
Event OnMessage stop publish message

### ISSUE THREAD

**Issue by izarraga** [mochi-co/mqtt#13]
Hi,
I just discovered this software and i liked it. Thanks.

One question:

I want to generate new messages to diferent topics based on original message, but i want to not publish the original.

Is posible to delete (not publish) a message ?

**Comment by mochi-co** [comment]
Hi @izarraga! It's currently not possible, but we can probably make it work! Could you tell me a little more about your use case so we can determine the best solution?

**Comment by izarraga** [comment]
Hi @mochi-co 

I have devices (GPS trackers) sending messages to servers.

Trackers  --> Socket Driver1 --> MQTT broker   --> Backend product 1
                     Socket Driver2                                    Backend product 2
                                                                                Backend product 3
                                                                                Backend product 4


All backends all receiving all message of trackers.  Witch is good because the same tracker can be used in diferents products at the same time, but all backend are discarting messages of trackers that are not for them.

That discard of messages consume CPU, bandwith, ....  It occurs to me to translate discarting logic to MQTT broker.


Other question:

I don't need to use persistence, but i want to not lost messages in backends reboots.  If i connect witch cleanSession=false and    QoS > 0  messages that arrive with backend in offline are later resend ?

**Comment by mochi-co** [comment]
Just to clarify - is there a single mqtt broker between all the backends, or is there an MQTT broker between each socket driver and backend product?

**Comment by mochi-co** [comment]
Ok thanks. I will have a think and get back to you with a possible solution!

**Comment by mochi-co** [comment]
@izarraga Follow up question - I am assuming that within the broker embedding code you have a mechanism that can determine if a client should receive a message based on the subscribed or client id? I'm guessing you have a situation where simply using topic filters per backend product is insufficient.

**Comment by izarraga** [comment]
Yes, your assumtion is correct.  I can't use topic filters.

Aside from my case.  I think being able to drop the message can be interesting for other cases.

Thanks.

**Comment by mochi-co** [comment]
@izarraga I have added a new `AllowClients` field to the packet structure, which allows you to specify one or more clients who are allowed to receive a message. See the latest release v1.0.3: https://github.com/mochi-co/mqtt/releases/tag/v1.0.3

Let me know if you have any questions!

> I don't need to use persistence, but i want to not lost messages in backends reboots. If i connect witch cleanSession=false and QoS > 0 messages that arrive with backend in offline are later resend ?

Without persistence, everything is stored in memory, so if your broker stops, everything will be cleared. The only way to maintain state across reboots is to use persistence. However, persistence writing mostly only comes into play if you are using `retain` on your messages, so unless you are persisting every message or running at maximum throughput, the performance difference won't be hugely noticeable. Feel free to open a new ticket if there's a separate issue here you'd like to explore.

**Comment by izarraga** [comment]
@mochi-co AllowClients solution is just perfect. Thank you.

Forget persistence question.  I have been doing tests and it works ok.
