### ISSUE TITLE
Order for inline client check

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#132]
Hi,

@mochi-co , are you ok in changing the order of all the inline checks, one example is:
from
`	if !s.hooks.OnACLCheck(cl, pk.TopicName, true) && !cl.Net.Inline {
		return nil
	}`
to
`	if !cl.Net.Inline && !s.hooks.OnACLCheck(cl, pk.TopicName, true) {
		return nil
	}`

This avoids unnecessary processing and error logs from custom ACL hook.

**Comment by mochi-co** [comment]
Yes absolutely, this is a great idea! I can do this or you can submit a PR if you already have changes 👍🏻

**Comment by thedevop** [comment]
I'll submit a PR.

**Comment by mochi-co** [comment]
Merged in v2.1.2 - Thank you @thedevop!
