### ISSUE TITLE
Support for X.509 Certificate based authentication

### ISSUE THREAD

**Issue by IshanDaga** [mochi-co/mqtt#136]
I would like to be able to use this mqtt package to authenticate incoming client connections based on a client key / certificate chain. Couldn't find and example for this in the given auth examples folder.

Will I be able to add this functionality using the provided `AddHook` or `AddListener` methods?

If not, is this something being worked on ? If not yet, I'd like to be able to contribute towards the same.

Thanks!

**Comment by IshanDaga** [comment]
Never mind, sorry about this, completely missed the TLS folder under examples.

**Comment by RangelReale** [comment]
@IshanDaga did you manage to do this? The TLS clientauth seems to work, but I don't seem to be able to get the certificates/client info from the hooks.

**Comment by IshanDaga** [comment]
Hey @RangelReale ! 
I referred to this discussion to move forward : https://github.com/mochi-co/mqtt/discussions/87
