### ISSUE TITLE
Subscribe RetainAsPublished misbehave with MQTT 3.1.1

### ISSUE THREAD

**Issue by bkupidura** [mochi-co/mqtt#141]
Currently every message received by 3.1.1 MQTT client, will have `retain` flag set to false. Even when it was published with retained flag set to true. 
MQTT 3.1.1 spec is not very specific about that, but previosly `retain` flag was set to whatever value was set in PUB packet.

This is because of https://github.com/mochi-co/mqtt/blob/0de1d731db5b4b94f580d1441560658303bdab2c/server.go#L788

AFAIK `RetainAsPublished` should be used only for v5 clients and for v3 it should be always set to `1`

**Comment by mochi-co** [comment]
I agree. I will try to fix this tomorrow if I get a chance, and push a new release.

**Comment by mochi-co** [comment]
This should be fixed in v2.1.5, try it out and let me know 👍🏻

**Comment by bkupidura** [comment]
@mochi-co its working as expected! Thank you!
