### ISSUE TITLE
Client can not connect if there are inherited retained messages

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#143]
If there are retained messages and the client is not connecting with CleanSession, it will result retained messages sent before the Connack.

In the inheritClientSession, it will call publishRetainedToClient before it has a chance to sendConnack.
https://github.com/mochi-co/mqtt/blob/300152413c0e3a35741329068cfe12c5c502274f/server.go#L346

In the inheritClientSession, it can make a copy of the existing subscriptions, but process them after it completes sendConnack.

If you like, I can create a PR.

**Comment by mochi-co** [comment]
Great discovery - I think you are correct. Yes, send over a PR and let's get it fixed! 

Thank you very much @thedevop

**Comment by mochi-co** [comment]
Fixed in v2.1.6
