### ISSUE TITLE
Improves Hooks thread safety

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#145]
Resurfacing this. @mochi-co , few things:

1. I agree that it is uncommon to add Hook after Serve.
3. I took advantage of atomicValue here because the content is a slice, and underlying content will not change, it will be append only. In case of reallocate, the old slice variable will still be valid (and consistent, but missing new entry), and new variable will be stored using atomic operation. Hence only Mutex is need for write, and no need for read.
4. This as you have pointed out, will not work with Map, unless you make a full copy of map during update, and store back the new map.
5. It is quite difficult to benchmark the difference. Based on my past experience, when < few hundred concurrency (not with long running lock), lock contentions are not too bad, but beyond that, it can be an issue. Given there are many hook points in the life cycle of a connection, when concurrent connections are high (we're looking to handle 200K+ per node), lock contentions become noticeable.
6. I appreciate keeping things consistent, it does make the code easier to understand/maintain. So there are 3 options:
   1. Revert to previous method (most performant) , but make doc more clear from `AddHook attaches a new Hook to the server. Ideally, this should be called before the server is started with s.Serve().` --> `AddHook attaches a new Hook to the server. This MUST be called before the server is started with s.Serve(). `
   2. Use atomic.Value
   3. Use current method with RWMutex, you may consider changing `append([]Hook{}, h.internal...)` to `hooks := h.internal`. The latter will not copy the underlying array, it will just copy the slice structure.

_Originally posted by @thedevop in https://github.com/mochi-co/mqtt/issues/135#issuecomment-1376545473_

**Comment by mochi-co** [comment]
I have been thinking about it this week, and I agree with all your points. I've made pr #148 reflecting this changes, if you'd like to review it. I think there's also optimisations to be had in other key slices/maps.

**Comment by mochi-co** [comment]
Fixed in v2.1.6
