### ISSUE TITLE
Using an existing listener to serve incoming connections

### ISSUE THREAD

**Issue by jeroenrinzema** [mochi-co/mqtt#154]
Hi 👋, I have been playing around a bit with the MQTT protocol and would like to use an existing TCP net.Listener to serve incoming connections. This would allow for multiplexing over a single net listener. Is this a change you are willing to accept into your Repo? I could open MR to include the changes.

**Comment by mochi-co** [comment]
Hi @jeroenrinzema! Yes this sounds very interesting. If it is significantly different to the existing TCP listener, or would cause breaking changes to the existing listener, add it as a new listener (e.g. `listeners/tcp_multiplex.go`). PRs are always welcome. I would love to see it!

Thank you

**Comment by jeroenrinzema** [comment]
I would like to suggest to introduce an API which simply accepts a `net.Listener`. I will open a MR including the changes.

**Comment by jeroenrinzema** [comment]
@mochi-co I have just opened a MR #155. Feel free to take a look and let me know what you think!
