### ISSUE TITLE
The client.refreshDeadline method should not be used within the client.WritePacket method. It will cause the device to be online for a long time even if it is offline

### ISSUE THREAD

**Issue by yemaozihecha** [mochi-co/mqtt#156]
```
// WritePacket encodes and writes a packet to the client.
func (cl *Client) WritePacket(pk packets.Packet) error {
	if atomic.LoadUint32(&cl.State.done) == 1 {
		return ErrConnectionClosed
	}

	if cl.Net.Conn == nil {
		return nil
	}

	defer cl.refreshDeadline(cl.State.keepalive)
	....
}
```

**Comment by mochi-co** [comment]
Hi @yemaozihecha! This is an interesting find. Originally, the logic behind this is that the client deadline should be extended if the server successfully communicates/writes a packet to the client. However, in this case the defer statement means refreshDeadline is called even if the write failed. 

I will remove the defer statement and relocate the statement until after successful packet transmission.

Thank you!

**Comment by mochi-co** [comment]
This should be resolved in v2.1.7

**Comment by mochi-co** [comment]
The more I have thought about this, the more I am thinking we no longer need refreshDeadline in write, as we should be resetting it whenever we receive a ping request from the client. I may remove it in v2.2.0 which involves the changes for #150

**Comment by yemaozihecha** [comment]
I think it should be used in client.ReadPacket, because the client's ping request can let you know whether the client is alive, but it is not needed in client.WritePacket.

**Comment by mochi-co** [comment]
In v2.2.0 in #165 I have remove the refreshDeadline from client.WritePacket, as you are correct @yemaozihecha - hopefully it will be released soon, if not I will issue it as a separate minor release.

**Comment by mochi-co** [comment]
This is resolved now in https://github.com/mochi-co/mqtt/releases/tag/v2.2.0 - thank you for highlighting it @yemaozihecha!
