### ISSUE TITLE
Max Connection Limit

### ISSUE THREAD

**Issue by fuadarradhi** [mochi-co/mqtt#164]
i want to use mqtt to develop a chat application,
I really like the mochi/mqtt package because it has a hook feature that really suits my needs.

i want to make sure before starting using, how many devices can connect to mochi/mqtt. is there a limit?

**Comment by thedevop** [comment]
There is no limit from the module perspective. However, system CPU, memory or external factors can be your limiting factors.

**Comment by fuadarradhi** [comment]
thanks for the response

if i have a vps with 4 cpu and 16 ram is it possible to get 100k+ connections,
or I need to upgrade the server ?

**Comment by thedevop** [comment]
YMMV, here are some [real-world performance data](https://github.com/mochi-co/mqtt/issues/117#issuecomment-1407758244).

**Comment by fuadarradhi** [comment]
thanks, this is very helpful

**Comment by mochi-co** [comment]
> YMMV, here are some [real-world performance data](https://github.com/mochi-co/mqtt/issues/117#issuecomment-1407758244).

@thedevop Please feel free to add some of this information to performance section of the README if you would like, it might be helpful to others 🙂
