### ISSUE TITLE
reconnection problem when use same client id 

### ISSUE THREAD

**Issue by werbenhu** [mochi-co/mqtt#173]
BUG: If there is already a connection with a client ID, and another connection uses the same client ID to connect again, the new client cannot receive the subscription message, and the hook should call OnDisconnect() first when the new connection comes. , and then call OnConnect()

**Comment by thedevop** [comment]
Ensure the original client is not set to autoReconnect, otherwise both clients will take turn to connect and kick off the other client.

I just tried it with client not set to autoReconnect, and the new client with the same clientID is able to receive the subscription message.

@mochi-co , it is more logical to have OnDisconnect before OnConnect. But tricky given the current structure. BTW, in looking into this, I found cl.WritePacket is now no longer called by a single thread, so there can be multiple writes to the connection simultaneously.

**Comment by werbenhu** [comment]
我已收到你的邮件，我将在看到邮件后，尽快给你回复。

**Comment by werbenhu** [comment]
@thedevop Neither client has set to autoReconnect, but both of their Clean Session are set，you can try it again with Clean Session on.

**Comment by thedevop** [comment]
Thanks @werbenhu. I was able to reproduce the issue.

Below is a description of the issue:
1. Each connection is handled by its own Go routine, and stays in attachClient
2. When a new connection comes in with the same clientID, and let's assume for the rest of this discussion the previous connection (session) has cleanSession flag set, it will disconnect the previous connection (send out a disconn packet and potentially forcefully disconnect the connection) and unsubscribe all previous session topics, but it does not wait until the previous Go routine to exit
3. It will then add the new session
4. At a later time, the previous connection Go routine will detect the connection is lost, then it does a clean up
https://github.com/mochi-co/mqtt/blob/1e8f92210202b61beb7f9fd104b057ec0a8386db/server.go#L367-L371
5. This will remove the subscriptions of the previous session (normally not an issue as the new session probably didn't receive subscription yet), and delete the this clientID from Server.Clients (this is an issue, from the broker's perspective, this client doesn't exist any more)

In fact, if a 3rd session is created with the same clientID, it will now exhibit a different issue, both 2nd and 3rd session connections will exist on the broker, and broker state only thinks there is 3rd session.

@mochi-co , there are few potential solutions to this, for example, add an additional state, or move the clean up into cl.State.endOnce in cl.Stop, etc...

**Comment by werbenhu** [comment]
@thedevop  i solve it by the this [rp](https://github.com/mochi-co/mqtt/compare/master...werbenhu:tttmqtt:master), check client's stopCause if is ErrSessionTakenOver , if yes don't delete.

**Comment by thedevop** [comment]
Can not access the above link.

**Comment by thedevop** [comment]
Thanks @werbenhu , please see my comments there.

The more I think about the order or OnConnect (new connection) / OnDisconnect (previous session), the current state is accurate. The new connection (this is before establishing a session) does occur before disconnect of the previous session. There is another event OnSessionEstablished which occurs after OnDisconnect (previous session).

**Comment by werbenhu** [comment]
you are right. I can use OnSessionEstablished.

**Comment by werbenhu** [comment]
@thedevop i tried OnSessionEstablished(), it is also called after OnDisconnect().

the old and new connections are in two goroutines.

new one call inheritClientSession()  ->   old one end cl.Read() and call OnDisconnect ->  new one call OnSessionEstablished()

So OnDisconnect needs to be before cl.Read().

**Comment by torntrousers** [comment]
> BUG: If there is already a connection with a client ID, and another connection uses the same client ID to connect again, the new client cannot receive the subscription message, and the hook should call OnDisconnect() first when the new connection comes. , and then call OnConnect()

I think we've seen the same issue too so can test it out when this is out in a release

**Comment by mochi-co** [comment]
I'm going to have a think about the simplest way to solve this issue

**Comment by werbenhu** [comment]
@mochi-co I just tested it on mosquitto, it will not send a will message in the case of reconnection by a same client id, maybe it is possible to consider not calling OnDisconnect(), just add an OnReconnect() interface?

**Comment by thedevop** [comment]
@mochi-co , you may want make the entire expire block to check `isTakenOver == 0`
https://github.com/mochi-co/mqtt/blob/46babc89c82dd3ae4f45fbffb84ace8b75de1a7c/server.go#L365-L371
As both `cl.ClearInflights` and `s.UnsubscribeClient` are done in inheritClientSession already.

**Comment by mochi-co** [comment]
@thedevop I did try this briefly, however note that expire must also occur on client sessions which have not been taken over - i.e. clean session clients or those with 0 expiry interval which are set to expire immediately:

```go
expire := (cl.Properties.ProtocolVersion == 5 && cl.Properties.Props.SessionExpiryIntervalFlag && cl.Properties.Props.SessionExpiryInterval == 0) 
|| (cl.Properties.ProtocolVersion < 5 && cl.Properties.Clean)
```

**Comment by torntrousers** [comment]
Hello. I've updated to 2.2.4 and am still seeing a problem with reconnecting with the same client id. I test with a simple nodered flow with a single publisher and single subscriber on the same topic. The subscriber only receives messages every 2nd deploy of the nodered flow. Could i switch on verbose logging on Mochi or something to show you more info on what happens?

**Comment by thedevop** [comment]
`atomic.StoreUint32(&existing.State.isTakenOver, 1)` needs to be in the if block before `return false` as well.

https://github.com/mochi-co/mqtt/blob/46babc89c82dd3ae4f45fbffb84ace8b75de1a7c/server.go#L444-L450

**Comment by werbenhu** [comment]
@thedevop Thanks, this issue has been resolved.

**Comment by torntrousers** [comment]
could it be out in  a release please so we can test it too?

**Comment by mochi-co** [comment]
Sorry for delay! Try https://github.com/mochi-co/mqtt/releases/tag/v2.2.5 and let me know! Thanks again @thedevop

**Comment by torntrousers** [comment]
Yes it works now for us with client reconnects. Thanks!
