### ISSUE TITLE
Large memory consumption with high concurrent connections

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#175]
On a node that is running with ~140K concurrent connections, using 2.1.6 it was consuming ~8GB of memory. However, after upgrade to 2.2.1, the application crash with OOM with ~100K using ~20+GB.

The culprit is:
https://github.com/mochi-co/mqtt/blob/1e8f92210202b61beb7f9fd104b057ec0a8386db/clients.go#L160

I was originally expecting only 8Bytes * MaximumClientWritesPending per client. However, after examining this more closely, this is using `chan packets.Packet` instead of `chan *packets.Packet`, which will use significantly more memory. Since this is last step in publishToClient, and no more modification will be made to the Packet either from this function or callers of publilshToClient, we can make outbound `chan *packets.Packet`.

**Comment by mochi-co** [comment]
Fixed in v2.2.3 - Thanks again! 🙂
