### ISSUE TITLE
OnConnectAuthenticate fail cause  cl.WriteLoop memory leaks.

### ISSUE THREAD

**Issue by likangjia** [mochi-co/mqtt#191]
the client verification failed because cl.State.outbound is not closed, resulting in the cl.WriteLoop block cannot be closed. How to handle memory leaks？

github.com/mochi-co/mqtt/v2/server.go:303
`

        if !s.hooks.OnConnectAuthenticate(cl, pk) { // [MQTT-3.1.4-2]

		err := s.sendConnack(cl, packets.ErrBadUsernameOrPassword, false)

		if err != nil {

			return fmt.Errorf("invalid connection send ack: %w", err)

		}

		return packets.ErrBadUsernameOrPassword
	}

	.......

	s.Log.Debug().Str("client", cl.ID).Err(err).Str("remote", cl.Net.Remote).Str("listener", listener).Msg("client disconnected")
	expire := (cl.Properties.ProtocolVersion == 5 && cl.Properties.Props.SessionExpiryIntervalFlag && cl.Properties.Props.SessionExpiryInterval == 0) || (cl.Properties.ProtocolVersion < 5 && cl.Properties.Clean)
	s.hooks.OnDisconnect(cl, err, expire)
	close(cl.State.outbound)`

**Comment by thedevop** [comment]
We can consider putting `close(cl.State.outbound)` in `cl.Stop`.

**Comment by likangjia** [comment]
At present, due to device migration or other reasons, the authentication of the device may always fail and cannot be completed correctly
