### ISSUE TITLE
when to delete closed client in clients internal map

### ISSUE THREAD

**Issue by youmisun** [mochi-co/mqtt#199]
```
type Clients struct {
	internal map[string]*Client // clients known by the broker, keyed on client id.
	sync.RWMutex
}
```
the closed client in internal map when to delete？

**Comment by thedevop** [comment]
Can you elaborate on the question?

**Comment by youmisun** [comment]
> Can you elaborate on the question?

if i have 1000 client disconnect from broker, the Clients internal map still keep this closed clients, this may case memory leak

**Comment by thedevop** [comment]
These clients will be deleted automatically if they're eligible:
https://github.com/mochi-co/mqtt/blob/7bd7bd5087c40f96015a61d01ce7ae4e6951c807/server.go#L375-L383

Also there is a ticker to clearExpiredClients:
https://github.com/mochi-co/mqtt/blob/7bd7bd5087c40f96015a61d01ce7ae4e6951c807/server.go#L1467

**Comment by youmisun** [comment]
> These clients will be deleted automatically if they're eligible:
> 
> https://github.com/mochi-co/mqtt/blob/7bd7bd5087c40f96015a61d01ce7ae4e6951c807/server.go#L375-L383
> 
> Also there is a ticker to clearExpiredClients:
> 
> https://github.com/mochi-co/mqtt/blob/7bd7bd5087c40f96015a61d01ce7ae4e6951c807/server.go#L1467

thanks!

**Comment by thedevop** [comment]
@youmisun , I forgot to mention, the default MaximumSessionExpiryInterval is [math](https://pkg.go.dev/math).[MaxUint32](https://pkg.go.dev/math#MaxUint32), you can lower this to something like 86400 (1 day).
