### ISSUE TITLE
new hook OnQuotaExceeded

### ISSUE THREAD

**Issue by izarraga** [mochi-co/mqtt#201]
Hi Mochi,

I think it would be interesting to have a hook when there is a error in NextPacketID().  

https://github.com/mochi-co/mqtt/blob/17fb7dadbc41b8ee379b7e18b8ec48621f33ae0c/server.go#L829

**Comment by mochi-co** [comment]
This seems reasonable to me 👍🏻

**Comment by izarraga** [comment]
Yes, better.

**Comment by mochi-co** [comment]
Added in v2.2.8 - sorry for the delay!

**Comment by izarraga** [comment]
Hi Mochi,

you have forgotten the line that invokes the hook

i, err := cl.NextPacketID() // [MQTT-4.3.2-1] [MQTT-4.3.3-1]
        if err != nil {
            s.Log.Warn().Err(err).Str("client", cl.ID).Str("listener", cl.Net.Listener).Msg("packet ids exhausted")
            s.hooks.OnPacketIDExhausted(cl, pk)
            return out, packets.ErrQuotaExceeded
        }

**Comment by mochi-co** [comment]
Ahh I'm terrible... I'll add that now. Sorry!

**Comment by mochi-co** [comment]
This should be available now in v2.2.9 :)
