### ISSUE TITLE
An error is reported when using the MQTTX client with last will to connect.

### ISSUE THREAD

**Issue by xtqxk** [mochi-co/mqtt#205]
https://github.com/mochi-co/mqtt/blob/46babc89c82dd3ae4f45fbffb84ace8b75de1a7c/packets/packets.go#L398

got error: WRN error="read connection: malformed packet: will properties"

**Comment by mochi-co** [comment]
This may be related to #206 - try v2.2.8 and let me know if it still occurs.

**Comment by xtqxk** [comment]
It's fixed on v2.28，Thx
