### ISSUE TITLE
client net.Conn in onConnect Hook

### ISSUE THREAD

**Issue by izarraga** [mochi-co/mqtt#21]
In onConnect event it would be interesting to be able to read client net.Conn. For example to view remoteAddr.

**Comment by jmacd** [comment]
This is fixed by #38, can close.

**Comment by mochi-co** [comment]
Great work 👍🏻

**Comment by mochi-co** [comment]
@jmacd I think the relevant code may be missing from v1.1.2 branch.

**Comment by mochi-co** [comment]
@jmacd @izarraga I see that `v1.2.0` provides the `RemoteAddr()` for the client in the new event client structure (I believe this is what you were referring to about @jmacd):

```go
events.Client{
	ID:       cl.ID,
	Remote:   addr, // Client remote address
	Listener: cl.Listener,
}
```

I'm going to close this issue as it means the example provided by @izarraga (remote address), and I'm not sure how useful exposing the entire `net.Conn` value set is - I am going to err on the side of minimalism. If there is a need for more data or functionality, let's open it in a new issue. 👍🏻
