### ISSUE TITLE
how to receive message and send message websocket mqtt

### ISSUE THREAD

**Issue by Firhan384** [mochi-co/mqtt#225]
hey, i wanna know, how get those function??

**Comment by mochi-co** [comment]
Hi @Firhan384, which part of the process are you looking for information on?

To use the broker with websockets run it with a websocket listener (see examples/tcp) and then use a js mqtt client like https://github.com/mqttjs/MQTT.js to connect.

**Comment by mochi-co** [comment]
@Firhan384 The simplest way is to have your client subscribe to a topic, eg. my/test/topic, and then you can publish messages to that topic using the direct publish method, for example:

```go
//  Publish(topic string, payload []byte, retain bool, qos byte)
err := server.Publish("direct/publish", []byte("packet scheduled message"), false, 0)
if err != nil {
   server.Log.Error().Err(err).Msg("server.Publish")
}
```

There's some example usage in examples/hooks/main.go :)

**Comment by Firhan384** [comment]
your example hook using tcp, not using websocket.

**Comment by mochi-co** [comment]
See https://github.com/mochi-co/mqtt/blob/master/examples/websocket/main.go - just add a websocket listener instead of the tcp listener - everything else is the same.

```go
server := mqtt.New(nil)
_ = server.AddHook(new(auth.AllowHook), nil)

ws := listeners.NewWebsocket("ws1", ":1882", nil)
err := server.AddListener(ws)
if err != nil {
    log.Fatal(err)
}
```

**Comment by Firhan384** [comment]
this is my main.go
<code>
func main() {
	tcpAddr := flag.String("tcp", ":1883", "network address for TCP listener")
	wsAddr := flag.String("ws", ":1882", "network address for Websocket listener")
	infoAddr := flag.String("info", ":8080", "network address for web info dashboard listener")
	flag.Parse()

	sigs := make(chan os.Signal, 1)
	done := make(chan bool, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)
	go func() {
		<-sigs
		done <- true
	}()

	server := mqtt.New(nil)
	_ = server.AddHook(new(auth.AllowHook), nil)

	tcp := listeners.NewTCP("t1", *tcpAddr, nil)
	err := server.AddListener(tcp)
	if err != nil {
		log.Fatal(err)
	}

	err = server.AddHook(new(ExampleHook), map[string]any{})
	if err != nil {
		log.Fatal(err)
	}

	ws := listeners.NewWebsocket("ws1", *wsAddr, nil)
	err = server.AddListener(ws)
	if err != nil {
		log.Fatal(err)
	}

	stats := listeners.NewHTTPStats("stats", *infoAddr, nil, server.Info)
	err = server.AddListener(stats)
	if err != nil {
		log.Fatal(err)
	}

	go func() {
		err := server.Serve()
		if err != nil {
			log.Fatal(err)
		}
	}()
	go func() {
		cl := server.NewClient(nil, "local", ws.ID(), true)
		for range time.Tick(time.Second * 10) {
			err := server.InjectPacket(cl, packets.Packet{
				FixedHeader: packets.FixedHeader{
					Type: packets.Publish,
				},
				TopicName: "direct/publish",
				Payload:   []byte("p"),
			})
			if err != nil {
				server.Log.Error().Err(err).Msg("server.InjectPacket")
			}
			server.Log.Info().Msgf("main.go injected packet to direct/publish")
		}
	}()

	<-done
	server.Log.Warn().Msg("caught signal, stopping...")
	server.Close()
	server.Log.Info().Msg("main.go finished")
}

type ExampleHook struct {
	mqtt.HookBase
}

func (h *ExampleHook) ID() string {
	return "events-example"
}

func (h *ExampleHook) Provides(b byte) bool {
	return bytes.Contains([]byte{
		mqtt.OnConnect,
		mqtt.OnDisconnect,
		mqtt.OnSubscribed,
		mqtt.OnUnsubscribed,
		mqtt.OnPublished,
		mqtt.OnPublish,
	}, []byte{b})
}

func (h *ExampleHook) Init(config any) error {
	h.Log.Info().Msg("initialised")
	return nil
}

func (h *ExampleHook) OnConnect(cl *mqtt.Client, pk packets.Packet) {
	h.Log.Info().Str("client", cl.ID).Msgf("client connected")
}

func (h *ExampleHook) OnDisconnect(cl *mqtt.Client, err error, expire bool) {
	h.Log.Info().Str("client", cl.ID).Bool("expire", expire).Err(err).Msg("client disconnected")
}

func (h *ExampleHook) OnSubscribed(cl *mqtt.Client, pk packets.Packet, reasonCodes []byte) {
	h.Log.Info().Str("client", cl.ID).Interface("filters", pk.Filters).Msgf("subscribed qos=%v", reasonCodes)
}

func (h *ExampleHook) OnUnsubscribed(cl *mqtt.Client, pk packets.Packet) {
	h.Log.Info().Str("client", cl.ID).Interface("filters", pk.Filters).Msg("unsubscribed")
}

func (h *ExampleHook) OnPublish(cl *mqtt.Client, pk packets.Packet) (packets.Packet, error) {
	h.Log.Info().Str("client", cl.ID).Str("payload", string(pk.Payload)).Msg("received from client")

	pkx := pk
	if string(pk.Payload) == "hello" {
		pkx.Payload = []byte("hello world")
		h.Log.Info().Str("client", cl.ID).Str("payload", string(pkx.Payload)).Msg("received modified packet from client")
	}

	return pkx, nil
}

func (h *ExampleHook) OnPublished(cl *mqtt.Client, pk packets.Packet) {
	h.Log.Info().Str("client", cl.ID).Str("payload", string(pk.Payload)).Msg("published to client")
}
</code>

this is my html
<code>
<!DOCTYPE HTML>

<html>
   <head>
      
      <script type = "text/javascript">

         function WebSocketTest() {
            if ("WebSocket" in window) {
               // Let us open a web socket
               var ws = new WebSocket("ws://localhost:1882/direct/publish");
				
               ws.onmessage = function (evt) { 
                  var received_msg = evt.data;
                  console.log('onmessage', evt)
                  alert("Message is received..." + JSON.stringify(received_msg));
               };
				
               ws.onclose = function() { 
                  
                  // websocket is closed.
                  alert("Connection is closed..."); 
               };
            } else {
              
               // The browser doesn't support WebSocket
               alert("WebSocket NOT supported by your Browser!");
            }
         }
      </script>
		
   </head>
   
   <body>
      <div id = "sse">
         <a href = "javascript:WebSocketTest()">Run WebSocket</a>
      </div>
      
   </body>
</html>
</code>

when i run the main.go, the web should get the data from websocket, but i cannot get it.

**Comment by mochi-co** [comment]
@Firhan384 I think your websocket address is incorrect, and should probably be `ws://localhost:1882`. WebSocket is simply a Layer 7 protocol like HTTP, and while MQTT can be configured to transmit on websocket, websocket doesn't have any inherent capacity to handle MQTT traffic. In order to use MQTT with websockets, you will need to use a javascript MQTT client such as MQTT.js.

In order to use In order to receive a message from a specific topic, you first need to subscribe to it - see the example on (https://github.com/mqttjs/MQTT.js#example.

Also see this image on a basic MQTT traffic flow to get a better idea of how it works: 
![](https://upload.wikimedia.org/wikipedia/commons/thumb/8/82/MQTT_protocol_example_without_QoS.svg/1920px-MQTT_protocol_example_without_QoS.svg.png)

In the case of the main.go example above, mochi-co/mqtt is both the broker and client B.
