### ISSUE TITLE
Questions about packet override (message inceptors)

### ISSUE THREAD

**Issue by luohao123** [mochi-co/mqtt#228]
Hell, this lib looks very promising, I want ask 2 quesitons:

1. will this lib keep updating ( I found many pouplar golang lib are don't maintaiend anylonger when many users use it  this is very painful);
2. Does there any examples on message inceptors for overrite incoming packets?

thanks inadvance!

**Comment by mochi-co** [comment]
@luohao123 I haven't tested this code but something like this should work:
```go


type MessageBody struct {
	Something string `json:"something"`
	Other int `json:"other"`
}

func (h *ExampleHook) OnPublish(cl *mqtt.Client, pk packets.Packet) (packets.Packet, error) {
	if pk.TopicName != "special/override" {
		return pk, nil
	}

	pkx := pk
	var m MessageBody
	err := json.Unmarshal(pkx.Payload, &m)
	if err != nil {
		return pkx, err
	}

	m.Something = "override"

	pkx.Payload, err = json.Marshal(m)
	if err != nil {
		return pkx, err
	}

	return pkx, nil
}
```
