### ISSUE TITLE
Panic: concurrent write to websocket connection

### ISSUE THREAD

**Issue by gumpyoung** [mochi-co/mqtt#232]
I've encountered panic with concurrent write to websocket connection randomly.

Per gorilla's documentation: https://pkg.go.dev/github.com/gorilla/websocket#hdr-Concurrency

Applications are responsible for ensuring that no more than one goroutine calls the write methods (NextWriter, SetWriteDeadline, WriteMessage, WriteJSON, EnableWriteCompression, SetCompressionLevel) concurrently and that no more than one goroutine calls the read methods (NextReader, SetReadDeadline, ReadMessage, ReadJSON, SetPongHandler, SetPingHandler) concurrently.

Wondering this issue can be fixed by adding a mutex lock to wsConn, I have forked the repo and will do more tests:

```
type wsConn struct {
	writeLock sync.Mutex
	net.Conn
	c *websocket.Conn
}

...
func (ws *wsConn) Write(p []byte) (int, error) {
	ws.writeLock.Lock()
	defer ws.writeLock.Unlock()
	err := ws.c.WriteMessage(websocket.BinaryMessage, p)
	if err != nil {
		return 0, err
	}

	return len(p), nil
}

```
panic: concurrent write to websocket connection

goroutine 228 [running]:
github.com/gorilla/websocket.(*messageWriter).flushFrame(0x14000743168, 0x1, {0x1400355a2cf?, 0x1400355e2d0?, 0x4d?})
        /Users/steven/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:617 +0x46c
github.com/gorilla/websocket.(*Conn).WriteMessage(0x1400062e9a0, 0x1006c7398?, {0x1400355a280, 0x4f, 0x80})
        /Users/steven/go/pkg/mod/github.com/gorilla/websocket@v1.5.0/conn.go:770 +0xf4
github.com/mochi-co/mqtt/v2/listeners.(*wsConn).Write(0x1290b3d38?, {0x1400355a280?, 0x4f, 0x14000680480?})
        /Users/steven/go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.7/listeners/websocket.go:167 +0x38
net.(*Buffers).WriteTo(0x14003512360, {0x128e14ba0?, 0x1400316c6f0?})
        /opt/homebrew/Cellar/go/1.20.2/libexec/src/net/net.go:730 +0xc4
github.com/mochi-co/mqtt/v2.(*Client).WritePacket(_, {{{{0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...}, ...})
        /Users/steven/go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.7/clients.go:554 +0x428
github.com/mochi-co/mqtt/v2.(*Client).WriteLoop(0x14000648240)
        /Users/steven/go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.7/clients.go:188 +0x94
created by github.com/mochi-co/mqtt/v2.(*Server).NewClient
        /Users/steven/go/pkg/mod/github.com/mochi-co/mqtt/v2@v2.2.7/server.go:222 +0x1a4

**Comment by thedevop** [comment]
Prior to v2.2.8, there were unsafe concurrent writes, #196. Can you upgrade to the latest (at least v2.2.8) and see if that resolves the issue.

**Comment by gumpyoung** [comment]
Thanks a lot @thedevop , re-tested with v2.2.10, the issue is gone.
I closing this ticket now.
