### ISSUE TITLE
MQTT v5 CONNACK control

### ISSUE THREAD

**Issue by thedevop** [mochi-co/mqtt#236]
Hi @mochi-co , with MQTT v5, many additional CONNACK reason codes are added (for example; 0x89, 0x9C, 0x9F). However, with the current OnConnect hook, application is not able to influence and return these as it doesn't provide return value(s).

We can either:
1. add a new hook, which is somewhat redundant to OnConnect
2. or modify OnConnect to provide return value(s), but it will break existing API

Note, for some of these reason codes, there are additional values in addition to the status code itself.

What's your thought on this?

**Comment by dgduncan** [comment]
@thedevop Do you mean create a new hook in order to be able to edit the CONNACK inflight?

**Comment by thedevop** [comment]
@dgduncan, to that effect. Currently OnConnect and OnConnectAuthenticate hooks are called before the CONNACK is sent. However, OnConnect is information only with no returned values, and OnConnectAuthenticate is hardcoded only to return ErrBadUsernameOrPassword upon authentication failure. There is no way to influence other return codes in CONNACK. The 2 options above is using returned value to influence the construct of CONNACK. What you proposed may even be better (for advanced users though), it is a more direct way to manipulate the CONNACK packet itself, kind like OnPublish.

**Comment by dgduncan** [comment]
Oh so you mean to change the signature of OnConnectAuthenticate as to allow more detail to be returned to the user via the expanded capability of V5, perhaps even exposed to implementors of the server via a hook so the logic can be offloaded to the implementor of the server and not in the server logic itself?

**Comment by thedevop** [comment]
Correct. Perhaps on OnConnect instead of OnConnectAuthenticate. An example use case could be, an broker is overloaded, and redirect new connections to another broker. MQTTv5 supports server redirection (like HTTP 301/302) in CONNACK or DISCONNECT.

**Comment by mochi-co** [comment]
@thedevop @dgduncan 

First, in an informal note - please allow my apologies for being somewhat less present lately - life has keeping me quite busy (and occasionally away from the internet), but rest assured I am keeping up with the PRs and issues and thinking about them as I have time. Your PRs are gratefully received and I really appreciate the thoughtfulness of the development that's been happening!

I think this is a very interesting idea that poses some challenges. I do like the idea of redirecting if the server is overloaded as this is a very clear use case to work toward. 

On the one hand, the simplest solution is to provide some kind of return from OnConnect. However, while this could provide a reason code, it doesn't provide the necessary extra information as @thedevop mentioned. On the other hand, there's a line of thought that would implement a new OnConnack hook to be called _either_ before the connack packet is handled in SendConnect (taking the code and present params), or after the packet has been created in SendConnack but before it is issued by writeClient. However, this doesn't provide a mechanism for exiting after OnConnect with an arbitrary connack.

I am hesitant to modify OnConnectAuthenticate to this end as it violates the purpose of the hook.

Another solution could be to export (sendConnack > SendConnack) and give it a properties parameter, and have OnConnect return an _ok, error_ value to potentially end the connection. This way SendConnack could be called from OnConnect (or any other place) by developers directly.

Look forward to hearing your thoughts!

**Comment by dgduncan** [comment]
I love this idea and it fits well with the increased capabilities of V5.

**Comment by thedevop** [comment]
Given Packet is comprehensive of all the possible info in a packet, maybe we can follow similar approach as OnPublish, which returns a packet and err. If err != nil, then sendConnack can then take that packet and override necessary fields like FixedHeader before WritePacket?

**Comment by mochi-co** [comment]
@thedevop My main issue with this approach is it requires OnConnect to return a fully compliant Connack packet, which opens up a sizeable window for developer-error. If we are relying on the developer to create packets in OnConnect to return, I think I would feel more comfortable with my suggestion above - allowing them to call SendConnack with all the required parameters. 

Also, it hasn't been discussed yet but anyone looking for more control can already directly call `func (cl *Client) WritePacket(pk packets.Packet) error` on the client passed to OnConnect, or any other hook. 

I have a bit of time tonight so I'll implement the changes above and get them pushed out with any other changes 👍🏻

**Comment by mochi-co** [comment]
This has been released in [v2.2.13](https://github.com/mochi-co/mqtt/releases/tag/v2.2.13) - Please let me know if this meets your needs and/or if we need to make any additional changes :)

**Comment by thedevop** [comment]
Now I got what you mean taking a property parameter. This should be good for the use case (do wish the SendConnack is done by the library instead thought).  Great point on WritePacket, this should give us the most control.

**Comment by thedevop** [comment]
Confirmed release v2.2.13 address this. Thanks!
