### ISSUE TITLE
how to check device connection status

### ISSUE THREAD

**Issue by Libong** [mochi-co/mqtt#246]
Hello, I would like to ask if it is feasible for me to implement OnDisconnect and OnConnect to determine the online status of the device?

If a device reconnects to mqtt without disconnecting, reconnecting to the same clientId and username will disconnect the previous connection, but OnConnect will be triggered first and then OnDisconnect will cause the device to reconnect. However, based on the final OnDisconnect, I will determine that it is offline

Or is there any other good way to handle the device status in this situation

**Comment by dgduncan** [comment]
@Libong There are a few ways to go about this:

- If you want to stick with only the hooks, you should most likely take a look at using `OnDisconnect` and `OnSessionEstablished`. It is quite common for OnDisconnect. to be fired after OnConnect and thusly leaving you with an incorrect value of online or offline if updating a database. `OnSessionEstablised` gives you a slightly more accurate look into if it is online.
- If you are using V5, you can use LWT with a Will Delay Interval that are both marked as `retain`. This will give you a decent approximation of online or offline during network drops; however, the data can be incorrect during that Will Delay Interval
- You can expose some sort of rpc endpoint that directly using the `*Clients` struct to get the most recent status from the struct itself; however, this should be avoided as if not done properly can have big knock on effects.
- Use a ping type command in which you send a command to the device over the broker with a response topic and correlation data (V5)

All this to say, there are levels you can go on how important knowing if a device is Online or Offline; however, the nature of MQTT makes it hard to say that with absolute certainty. I tend to look at it as not Online or Offline, but Available or Unavailable.

**Comment by thedevop** [comment]
There is a method Closed() (#130) for client can help you determine that.

**Comment by Libong** [comment]
Thank you for your feedback, but what I want to do is update the status in real time, and calling the closed function will have some latency. It would be strange to call it in the ondisconnect implementation.

However, the positions of OnSessionEstablished and Onconnect calls are both close to each other in the attachClient. My current situation is that after a device successfully connects, another device connects with the same connection parameters (the same client) and somehow closes the previous client to create a new one. In err=cl.Read (s. receivePacket), a use of closed network connection will be reported, and then err will be passed into OnDisconnect

So currently, we can only determine the err in OnDisconnect by

If there are any better suggestions, I hope you can provide them. Thank you

**Comment by thedevop** [comment]
Is the goal to determine a connection is disconnected (OnDisconnect) because the client is taken over by another connection with the same clientID. If so, then there is `isTakenOver` in the ClientState indicating that. We can have an exported function to expose that information.

**Comment by Libong** [comment]
Okay, thank you for your reply

**Comment by leandrofars** [comment]
Hi, anyone has a definitive solution for having a trustable trace of connected and disconnected devices? A code snippet of how to set up the hooks or to expose the client map would help.
The issue I'm with happens when the broker is at a high traffic load and the same device connects and disconnects frequently.
