### ISSUE TITLE
Do not disconnect existing session for new connection auth failures

### ISSUE THREAD

**Issue by jmacd** [mochi-co/mqtt#35]
In `Server.EstablishConnection()` there is an authorization test, and even if the test fails it first checks whether there's a session present and disconnects the other, valid session. This could lead to an invalid connection disrupting a valid connection.

It seems unintentional. Presumably MQTT does not require a correct response for `sessionPresent` when authorization has failed.

**Comment by mochi-co** [comment]
Fixed in `v1.2.0` 👍🏻
