### ISSUE TITLE
Howto create anonymous listener for testing

### ISSUE THREAD

**Issue by andig** [mochi-co/mqtt#6]
For testing I want to use an anonymous server port like in `httptest`:

	tcp := listeners.NewTCP("t1", "")

Doing so works, but I habe no option to retrieve the port as the TCP listener is private.

Alternatively, it would be nice if the listener could be created and passed into the server on the consumer side.

**Comment by mochi-co** [comment]
Hi @andig - If you are just using it for testing, you could create a mock listener using the `Listener` interface https://github.com/mochi-co/mqtt/blob/master/server/listeners/listeners.go#L31

Otherwise you will need to specify a port when creating the TCP listener, for example:

```
tcp := listeners.NewTCP("t1", ":1883")
```

**Comment by andig** [comment]
Thank you for the quick response. I must admit that I've given up and moved to a library that allows to provide your own listener. Imho that would be a preferable pattern if possible. Please feel free to close.

**Comment by mochi-co** [comment]
No worries @andig. Note that you can create your own Listeners of any kind using the `Listener` interface above. Some examples are provided:

A mock listener:
https://github.com/mochi-co/mqtt/blob/master/server/listeners/mock.go

TCP listener:
https://github.com/mochi-co/mqtt/blob/master/server/listeners/tcp.go

Websocket listener:
https://github.com/mochi-co/mqtt/blob/master/server/listeners/websocket.go
