### ISSUE TITLE
Internal publish

### ISSUE THREAD

**Issue by wz2b** [mochi-co/mqtt#7]
When embedding this server, can the application doing the embedding publish a message to a topic directly?  If not, can that be added?

**Comment by mochi-co** [comment]
Hi @wz2b - currently this isn't supported, but it is on the roadmap (I got a bit busy with other life things). I can probably get this implemented in the next few days if you'd like?

**Comment by wz2b** [comment]
Sure.  Would you also need the ability to 'create topic' or would publishing do that automatically?   My alternative is I can make a loopback connection over localhost but that's messier if there is a way to expose this capability in Server.

 If you can expose a `server.Publish(topic, content)` or something similar, then I will help test.

**Comment by mochi-co** [comment]
I was thinking about this earlier this morning as there are a few ways to do it. In either case, there is no need to 'create topic' as the topic creation is handled when a) a client subscribes to a given topic, or b) a client publishes a retained message to a given topic. So just providing the ability to publish should be sufficient.

I am thinking of something like: `Publish(topic string, message []byte, retain bool) (messageID int, err error)`, which would directly be issued out to all topic subscribers. I have omitted the QoS byte as the embedder is directly interacting with the server, making QoS redundant in this case.

If we are adding inline publishing I think it also makes sense to provide an ability to read messages which have been received. The most useful solution would be to expose a channel of `server.Messages` to the embedding code which will stream the incoming messages while the channel is connected. The embedding service can then operate on this from a goroutine or worker pool. I will look at what I can do to expose a topic filtering function for the embedded service to use also.

Does this sound like it could work?

**Comment by mochi-co** [comment]
It wouldn't return an error as it's technically correct behaviour (you can publish a retain=1 message to a topic with no subscribers, who will then get the message when they subscribe to the topic). In theory it's possible to return a boolean to indicate if there were or weren't any subscribers at the time of publishing, but it'd take a bit of refactoring so it depends on your use case and how important it is to you...

Otherwise yes, it would work exactly as normal :)

**Comment by mochi-co** [comment]
@wz2b Release v1.0.1 is up, it contains the the direct `Publish` method, and an `onMessage` event hook. Performance effects appear to be negligible.

I've added a usage example in https://github.com/mochi-co/mqtt/blob/master/examples/events/main.go

The direct publish method looks like this:
(https://github.com/mochi-co/mqtt/blob/master/server/server.go#L358)
```go
// func (s *Server) Publish(topic string, payload []byte, retain bool) error
err := s.Publish("a/b/c", []byte("hello"), false)
if err != nil {
    log.Fatal(err)
}
```

and the event hook looks like this:
(https://github.com/mochi-co/mqtt/blob/master/server/events/events.go)
```go
import "github.com/mochi-co/mqtt/server/events"

server.Events.OnMessage = func(cl events.Client, pk events.Packet) (pkx events.Packet, err error) {
    if string(pk.Payload) == "hello" {
        pkx = pk
        pkx.Payload = []byte("hello world")
        return pkx, nil
    } 
    return pk, nil
}
```
I hope this helps. Let me know how it goes or if you have any questions or thoughts!

**Comment by wz2b** [comment]
You're ahead of me!  Give me a couple of days and let me try it all out.  Once I'm successful I'll close the issue out.  Thanks for taking the time to do this!!!!  Hopefully it's useful to other people besides me, but even if it's not, I still appreciate it very much.

**Comment by mochi-co** [comment]
@wz2b Did this all work out?
