### ISSUE TITLE
Update Benchmarks for v1.3.0

### ISSUE THREAD

**Issue by mochi-co** [mochi-co/mqtt#71]
The benchmarks on the readme are a little out of date, it would be good to refresh them.

**Comment by izarraga** [comment]
I have done some bechmarks MOCHI vs NATS.IO(mqtt plugin)

The server is a Raspberry PI 3

Results:

MOCHI
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=1 -num-messages=10000
1 worker started

# Configuration
Concurrent Clients: 1
Messages / Client:  10000

# Results
Published Messages: 10000 (100%)
Received Messages:  10000 (100%)
Completed:          1 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 118319 msg/sec
Slowest: 118319 msg/sec
Median: 118319 msg/sec

  < 118319 msg/sec  100%

# Receiving Througput
Fastest: 26415 msg/sec
Slowest: 26415 msg/sec
Median: 26415 msg/sec

  < 26415 msg/sec  100%


NATS.IO
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=1 -num-messages=10000
1 worker started

# Configuration
Concurrent Clients: 1
Messages / Client:  10000

# Results
Published Messages: 10000 (100%)
Received Messages:  10000 (100%)
Completed:          1 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 113405 msg/sec
Slowest: 113405 msg/sec
Median: 113405 msg/sec

  < 113405 msg/sec  100%

# Receiving Througput
Fastest: 102482 msg/sec
Slowest: 102482 msg/sec
Median: 102482 msg/sec

  < 102482 msg/sec  100%


MOCHI
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=10 -num-messages=10000
10 worker started

# Configuration
Concurrent Clients: 10
Messages / Client:  100000

# Results
Published Messages: 100000 (100%)
Received Messages:  100000 (100%)
Completed:          10 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 46749 msg/sec
Slowest: 17372 msg/sec
Median: 24140 msg/sec

  < 20310 msg/sec  10%
  < 23248 msg/sec  50%
  < 26185 msg/sec  70%
  < 29123 msg/sec  80%
  < 37936 msg/sec  90%
  < 49687 msg/sec  100%

# Receiving Througput
Fastest: 14172 msg/sec
Slowest: 8341 msg/sec
Median: 9748 msg/sec

  < 8924 msg/sec  10%
  < 9507 msg/sec  50%
  < 10090 msg/sec  70%
  < 10673 msg/sec  80%
  < 12423 msg/sec  90%
  < 14755 msg/sec  100%


NATS.IO
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=10 -num-messages=10000
10 worker started

# Configuration
Concurrent Clients: 10
Messages / Client:  100000

# Results
Published Messages: 100000 (100%)
Received Messages:  100000 (100%)
Completed:          10 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 29373 msg/sec
Slowest: 16874 msg/sec
Median: 23401 msg/sec

  < 18124 msg/sec  10%
  < 19374 msg/sec  20%
  < 21873 msg/sec  30%
  < 23123 msg/sec  50%
  < 24373 msg/sec  60%
  < 25623 msg/sec  80%
  < 26873 msg/sec  90%
  < 30623 msg/sec  100%

# Receiving Througput
Fastest: 13507 msg/sec
Slowest: 10996 msg/sec
Median: 12032 msg/sec

  < 11247 msg/sec  10%
  < 11499 msg/sec  20%
  < 11750 msg/sec  30%
  < 12001 msg/sec  40%
  < 12252 msg/sec  60%
  < 12503 msg/sec  70%
  < 13005 msg/sec  80%
  < 13256 msg/sec  90%
  < 13758 msg/sec  100%


MOCHI
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=500 -num-messages=1000
100 worker started - waiting 500ms
200 worker started - waiting 500ms
300 worker started - waiting 500ms
400 worker started - waiting 500ms
500 worker started

# Configuration
Concurrent Clients: 500
Messages / Client:  500000

# Results
Published Messages: 500000 (100%)
Received Messages:  500000 (100%)
Completed:          500 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 121972 msg/sec
Slowest: 414 msg/sec
Median: 5929 msg/sec

  < 12570 msg/sec  78%
  < 24726 msg/sec  90%
  < 36881 msg/sec  95%
  < 49037 msg/sec  96%
  < 61193 msg/sec  97%
  < 73349 msg/sec  98%
  < 85504 msg/sec  99%
  < 97660 msg/sec  99%
  < 109816 msg/sec  100%
  < 134127 msg/sec  100%

# Receiving Througput
Fastest: 6937 msg/sec
Slowest: 260 msg/sec
Median: 581 msg/sec

  < 927 msg/sec  80%
  < 1595 msg/sec  96%
  < 2263 msg/sec  99%
  < 2931 msg/sec  100%
  < 3598 msg/sec  100%
  < 7605 msg/sec  100%


NATS.IO
root@msi:~/mqtt-stresser# ./mqtt-stresser -broker tcp://192.168.11.50:1883 -no-progress -num-clients=500 -num-messages=1000
100 worker started - waiting 500ms
200 worker started - waiting 500ms
300 worker started - waiting 500ms
400 worker started - waiting 500ms
500 worker started

# Configuration
Concurrent Clients: 500
Messages / Client:  500000

# Results
Published Messages: 500000 (100%)
Received Messages:  500000 (100%)
Completed:          500 (100%)
Errors:             0 (0%)

# Publishing Throughput
Fastest: 136232 msg/sec
Slowest: 574 msg/sec
Median: 6366 msg/sec

  < 14140 msg/sec  74%
  < 27706 msg/sec  88%
  < 41272 msg/sec  94%
  < 54837 msg/sec  96%
  < 68403 msg/sec  97%
  < 81969 msg/sec  97%
  < 95534 msg/sec  97%
  < 109100 msg/sec  99%
  < 122666 msg/sec  99%
  < 136232 msg/sec  100%
  < 149797 msg/sec  100%

# Receiving Througput
Fastest: 17970 msg/sec
Slowest: 280 msg/sec
Median: 854 msg/sec

  < 2049 msg/sec  91%
  < 3818 msg/sec  96%
  < 5587 msg/sec  97%
  < 7356 msg/sec  97%
  < 9125 msg/sec  98%
  < 10894 msg/sec  98%
  < 12663 msg/sec  99%
  < 14432 msg/sec  99%
  < 16201 msg/sec  99%
  < 17970 msg/sec  100%
  < 19739 msg/sec  100%

**Comment by mochi-co** [comment]
Superseded by v2.0.0
