### ISSUE TITLE
Support TLS Client Certificates?

### ISSUE THREAD

**Issue by torntrousers** [mochi-co/mqtt#79]
Hi I'm looking for an embeddable MQTT broker and came across this project and it looks pretty good, but from a short look around i couldn't see that it supports using certificates to authorize mqtt clients, is that the case and if so would it be possible to add that?

It needs a way to set ```RequireAndVerifyClientCert``` on the [tls.ClientAuthType](https://pkg.go.dev/crypto/tls#ClientAuthTyp) on the TLS config being used by the server, and then some plugable way to manage the pool of client CA certificates.

**Comment by mochi-co** [comment]
Thanks @torntrousers - I think this is something we can and should add, so I will schedule it it in for the next set of changes.

**Comment by torntrousers** [comment]
Thanks @mochi-co ! Could you give me any idea what sort of timeframe are you are thinking? If I offered to help would it speed things up at all?

**Comment by torntrousers** [comment]
I don't know what nees to be done and haven't really look at any of the code yet :) so will wait at least for your bullet point list

**Comment by torntrousers** [comment]
Thanks! WIll go give it a try...

**Comment by torntrousers** [comment]
That does just what i needed. Thanks for the quick support!
